---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: result
  namespace: vote-app
  labels:
    app: result  
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
        - image: eddiedlopez/result-noarch:latest
          name: result
          ports:
          - containerPort: 80
            name: result
---
apiVersion: v1
kind: Service
metadata:
  name: result 
  labels: 
    app: result
spec:
  type: NodePort
  ports:
  - name: "results-service"
    port: 80
    targetPort: 80
    nodePort: 32001
  selector:
    app: result
