---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  labels: 
    role: vote
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1  
  replicas: 1
  revisionHistoryLimit: 3
  minReadySeconds: 20  
  selector:
    matchLabels:
      role: role
    matchExpressions:
      - key: version
        operator: Exists    
  template:
    metadata:
      name: vote
      labels:
        role: vote
        version: latest 
    spec:
      containers:
      - image: docker.io/eddiedlopez/vote:@sha256:35fbcbfbe4d65b3e9a89b5325a69d04b1e0938ba4289823524c7224d1b9c6812
        name: vote
        ports:
        - containerPort: 80
          name: vote
---
apiVersion: v1
kind: Service
metadata:
  name: vote
  labels:
    role: vote
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    role: vote
