apiVersion: apps/v1
kind: Deployment
metadata: 
  name: result
  namespace: vote-app
  labels:
    app: result  
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
        - image: dockersamples/examplevotingapp_result@sha256:c87f44054a409c8a457b19089efbb9bb039b4539af62b2f4906bf6f05d380c31
          name: result
          ports:
          - containerPort: 80
            name: result
               

