---
apiVersion: v1
kind: Service
metadata:
  labels:
    role: redis
  name: redis
  namespace: vote-app
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
