---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  labels: 
    role: ui
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1  
  replicas: 1
  revisionHistoryLimit: 3
  minReadySeconds: 20  
  selector:
    matchLabels:
      role: ui
    matchExpressions:
      - key: version
        operator: Exists    
  template:
    metadata:
      name: ui
      labels:
        role: ui
        version: latest 
    spec:
      containers:
      - image: docker.io/eddiedlopez/vote:latest
        name: ui
        ports:
        - containerPort: 80
          name: ui
---
apiVersion: v1
kind: Service
metadata:
  name: ui
  labels:
    role: ui
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    role: ui
