apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: vote-app
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 20
  selector:
    matchLabels:
      role: worker
  template:
    metadata:
      name: worker
      labels:
        app: java
        role: worker
        version: latest
    spec:
      containers:
        - image: eddiedlopez/worker-noarch
          name: worker
