apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: vote-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  minReadySeconds: 20
  template:
    metadata:
      labels:
        app: db
        role: db
        version: latest
    spec:
      containers:
      - image: postgres@sha256:dd15a3f9b9a11aa9f1c5a018a33e1ce62fc76ad0d2fca99953ab03b5969174c1
        imagePullPolicy: Always
        name: db
        env:
          - name: POSTGRES_HOST_AUTH_METHOD
            value: trust
        ports:
        - containerPort: 5432
          protocol: TCP
          name: postgres  
        volumeMounts:
        - name: db-pv
          mountPath: /var/lib/postgresql/data
          subPath: postgres
      volumes:
      - name: db-pv
        persistentVolumeClaim:
          claimName: db-pvc

