---
apiVersion: v1
kind: Service
metadata:
  labels:
    role: vote-db
  name: vote-db
  namespace: vote-app
spec:
  selector:
    role: vote-db
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
